name: Desplegando en Nginx EC2

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Deployment'
        description: 'Release Notes for Deployment with loadbalancer'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      # Step 3: Configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Terraform Init
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Apply Terraform changes
      - name: Apply Terraform changes
        run: terraform apply -auto-approve

      # Step 7: Output ELB DNS Name
      - name: Output Load Balancer DNS
        run: |
          echo "Extracting ELB DNS..."
          terraform output elb_dns_name